font:
  normal:
    family: "MesloLGS Nerd Font"
    style: "Regular"
  bold:
    family: "MesloLGS Nerd Font"
    style: "Bold"
  italic:
    family: "MesloLGS Nerd Font"
    style: "Italic"
  size: 20.0

window:
  opacity: 0.85
  decorations: "none"

colors:
  primary:
    background: '0x000000'
